default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    host: localhost
    database: salary_management_development
    username: <%= Rails.application.credentials.dig(:database, :development, :username) %>
    password: <%= Rails.application.credentials.dig(:database, :development, :password) %>

  queue:
    <<: *default
    host: localhost
    database: salary_management_development_queue
    username: <%= Rails.application.credentials.dig(:database, :development, :username) %>
    password: <%= Rails.application.credentials.dig(:database, :development, :password) %>
    migrations_paths: db/queue_migrate

test:
  <<: *default
  host: localhost
  database: salary_management_test
  username: <%= Rails.application.credentials.dig(:database, :test, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :test, :password) %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
